### ISSUE TITLE
Single Reader Analysis

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DIDSR/iMRMC#10]
```
iMRMC has been a useful tool in designing and powering future reader studies, 
and I really appreciate all the support and effort Dr. Gallas and his team has 
put into this product. 

My enhancement request is quite simply, the ability to analyze single reader 
study would a really value added proposition. Often smaller dry-run studies 
involving a single reader are executed before a moving to full study 
deployment. This tool to support would then be able to support study throughout 
its various stages: design, dry-run, and final analysis. 

Thank you again for the support. 
```

Original issue reported on code.google.com by `keay.ty...@gmail.com` on 6 May 2014 at 5:39

**Comment by brandon-gallas** [comment]
@koyousun

Yousun,

Please consider this issue. It is more sophisticated and will likely require significant contribution from Dr. Jeon. I already know how to do this by "tricking" the system with artificial input. If you and Dr. Jeon want to try this, let me know and I will prepare more details and instructions.

Brandon

**Comment by koyousun** [comment]
Got it.

**Comment by brandon-gallas** [comment]
@koyousun @jenjong @kholee 

I haven't heard from you in a while.
How is the single-reader analysis going?
I have another person (colleague) asking for software.
I am going to tell this colleague to create a data set with multiple readers by simply duplicating the single-reader data for additional fake readers. This is how you can trick the software to do a single-reader analysis.

Brandon

**Comment by koyousun** [comment]
@brandon-gallas @jenjong @kholee 
I am sorry for the delay in replying. This issue is in progress. Jong June and I are improving the code. I will get back to you within a week.

**Comment by qigongFDA** [comment]
We have implement a solution, the single-reader analysis is available on the Show AUC button and output file (Save Stat Analysis button, Analysis All Modalities button)
