### ISSUE TITLE
Export whole stat, each reader analysis result and ROC curve.

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/iMRMC#103]
We need a new button to export whole stat, each reader analysis result and ROC curve data at same time. 
whole stat, readers analysis:
Output should include all individual modality and their combinations analysis. 
ROC curve:
Output should include all modalities ROC curve.
Applicability:
We hope it could work for both raw data and summary input files.

**Comment by qigongFDA** [comment]
Add a new button "Save All Stat" in iMRMC.
It could analysis all modalities combinations study then exports study and each readers analysis results. 
At the same time, it exports ROC curve data. 
Now the button only available for raw reader data input file.

**Comment by qigongFDA** [comment]
Save All Stat button is available for summary input file. It could export whole study and each readers result. 
I temporarily use whole study case size as each readers read case size. Because we don't save these information in summary.

**Comment by qigongFDA** [comment]
Save All Stat button could export MLE analysis result for both raw data and summary input file.

For summary input analysis, Save All Stat button doesn't export each readers analysis result.

**Comment by qigongFDA** [comment]
1. Save All Stat button could create a folder in input file directory with name "input file name + time"
2. Analysis table, results, AUC and ROC information will save in that folder.
3. In exportToFile.java, create 5 methods to save analysis table.

**Comment by qigongFDA** [comment]
Could we close this issue?

**Comment by brandon-gallas** [comment]
This is excellent. I'm closing this issue.
