### ISSUE TITLE
iRoeMetz manual

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/iMRMC#104]
We need create a manual for iRoeMetz software by Dr.explain. It should include GUI and validation parts.

**Comment by brandon-gallas** [comment]
The FDA svn directory has other resources including an early draft of the iRoeMetz user manual. Please look at everything, determine if they have any value, and then propose a plan for each one: worthless delete, integrate into … and then delete.
FDAsvn\imrmc\branches\000fda_miscellaneous\user_manual

**Comment by qigongFDA** [comment]
I create my fork of iMRMC for first draft version of iRoeMetz and iMRMC manual.

**Comment by qigongFDA** [comment]
First draft version is done.
