### ISSUE TITLE
Run iMRMC by command 

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/iMRMC#106]
We want to run iMRMC software by command. And software should output the same thing as Save All Stat button.

**Comment by qigongFDA** [comment]
1. Create commandStartFunction.java class to run iMRMC by command line, in format (java -jar "compiled file name" "input file path and name".
2. Both raw and summary files could be loaded by command line. 
3. Create commandStart flag in MRMC.java to track the software is launched in GUI or command line. 
4. Add return function in InputFile.java. It avoids software crash, when user choose an invalid input file.

**Comment by qigongFDA** [comment]
Could we close this issue?

**Comment by brandon-gallas** [comment]
Have you written instructions in the user manual for doing the command line execution?

**Comment by qigongFDA** [comment]
I have wrote instructions about how to run it in command line. I will merge it in whole manual with Jessica.

**Comment by qigongFDA** [comment]
We could close this issue.

**Comment by brandon-gallas** [comment]
I have run this in windows and linux. I get the same error in both. Here is the output.

sim-15-01-22-17-49-14-00000.imrmc
Found NR: in header. NR= 5
Found N0: in header. N0= 50
Found N1: in header. N1= 50
Found NM: in header. NM= 2
a total of 11 lines in header
readerIDs: {1=0, 2=1, 3=2, 4=3, 5=4}
normalIDs: {1=0, 10=1, 11=2, 12=3, 13=4, 14=5, 15=6, 16=7, 17=8, 18=9, 19=10, 2=11, 20=12, 21=13, 22=14, 23=15, 24=16, 25=17, 26=18, 27=19, 28=20, 29=21, 3=22, 30=23, 31=24, 32=25, 33=26, 34=27, 35=28, 36=29, 37=30, 38=31, 39=32, 4=33, 40=34, 41=35, 42=36, 43=37, 44=38, 45=39, 46=40, 47=41, 48=42, 49=43, 5=44, 50=45, 6=46, 7=47, 8=48, 9=49}
diseaseIDs: {100=0, 51=1, 52=2, 53=3, 54=4, 55=5, 56=6, 57=7, 58=8, 59=9, 60=10, 61=11, 62=12, 63=13, 64=14, 65=15, 66=16, 67=17, 68=18, 69=19, 70=20, 71=21, 72=22, 73=23, 74=24, 75=25, 76=26, 77=27, 78=28, 79=29, 80=30, 81=31, 82=32, 83=33, 84=34, 85=35, 86=36, 87=37, 88=38, 89=39, 90=40, 91=41, 92=42, 93=43, 94=44, 95=45, 96=46, 97=47, 98=48, 99=49}
modalityIDs: {1=0, 2=1}
caseIDs: {}
Input Raw File Successfully Read!
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1911)
        at mrmc.gui.GUInterface$SaveAllStatListener.exportResult(GUInterface.java:637)
        at mrmc.core.cmonnandStartFunction.cmonnandStartFunction(cmonnandStartFunction.java:49)
        at mrmc.core.MRMC.main(MRMC.java:103)

**Comment by qigongFDA** [comment]
Maybe you didn't use the full path name for input file.

**Comment by brandon-gallas** [comment]
You are correct. I didn't read the instructions carefully enough. Thanks. It works in Windows.
Unfortunately, it doesn't work in Linux.

**Comment by brandon-gallas** [comment]
There was an update to version 3p0 that I didn't have.
It works as advertised.
Nice job.
