### ISSUE TITLE
ROC curve button - layout issues

### ISSUE THREAD

**Issue by suneeta** [DIDSR/iMRMC#108]
Hi, I just noticed that ROC curve button does not render when app window is smaller. Looks to be a layout issue because it shows up up when window is much larger. Looked through existing issues to see you guys know about it already but I could not find any. Please ignore if you know about it already! 

<img width="934" alt="screen shot 2016-08-23 at 8 35 28 am" src="https://cloud.githubusercontent.com/assets/4206224/17874054/9a3e1bd6-690c-11e6-85ce-9292b9059b17.png">

**Comment by qigongFDA** [comment]
@suneeta 
Thank you for your issue. We didn't find this problem before. I want to know "Why you want to make the window small? Does the default size larger than your screen?". This could help us solve the problem better. Thank you.

Qi

**Comment by suneeta** [comment]
I think its more related to usability issue. I prefer small windows. 
I also noticed some other minor issues like asking to save reports and cancelling confirmation dialog creates the directory anyway. Similarly few other minor issues. Just wanted to let you know, Incase If you feel these are worthy to investigate basing on what the expectations are.

**Comment by brandon-gallas** [comment]
We want the feedback. All of it. Logging them as separate issues would allow us to prioritize, but we'll take what you give.
We will consider a more compact gui as time allows. Another solution for the large window problem is to run iMRMC command line. I'm not sure documentation is up to date with this feature described.
@qigongFDA, please provide documentation so Suneeta can run iMRMC on the command line.

**Comment by qigongFDA** [comment]
Hello @suneeta 

You can use the following links to find latest PDF and HTML version manuals. (They are draft manuals, so there are watermarks on all images)
http://didsr.github.io/iMRMC/000_iMRMC/userManualHTMLdraft/index.htm
http://didsr.github.io/iMRMC/000_iMRMC/userManualPDFdraft/iMRMCuserManual.pdf

Section "3.2 Command Line" provides information about how to run iMRMC by command line. 

Thank you,
Qi

**Comment by qigongFDA** [comment]
Reorganize buttons and hide variance component table by a button. The whole GUI is more compact. Can we close the issue?

**Comment by brandon-gallas** [comment]
We can close it once it has been merged in the master branch.

**Comment by qigongFDA** [comment]
This is done.
