### ISSUE TITLE
Library License 

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/iMRMC#110]
With our software development, we will include more and more libraries. We should pay attention of the libraries license ( Proprietary or free and open source (permissive, weak copyleft, copyleft)).

There are several useful links about license.   
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3406002/
https://www.gnu.org/licenses/license-list.en.html

**Comment by brandon-gallas** [comment]
Please define permissive, weak copyleft, and copyleft before the licenses in LICENSE.md, provide the links to the resources about licenses (these are the references for the definitions), and then label each license accordingly.

**Comment by qigongFDA** [comment]
This is Done.
