### ISSUE TITLE
Specify output directory during command-line execution: Non-interactive

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#112]
Right now we can run iMRMC from the command line in a non-interactive way. Here is the command:
java -jar iMRMC-v3p0.jar inputFileName.imrmc
The program creates an output folder with all the analysis results; the name is constructed as the inputFileName with a TimeStamp. I would like to specify the name of the output folder on the command line as follows:
java -jar iMRMC-v3p0.jar inputFileName.imrmc outputFolder

Is this possible?
This will make it easier to access the results from inside other software. Right now I am creating an input file in R and calling the iMRMC program. It is hard to access the results because I don't know the outputFolder. I don't know the timestamp.

B

**Comment by qigongFDA** [comment]
This is Done
