### ISSUE TITLE
bad format output file AUCperReader.csv

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#113]
I have a data set where one of the readers gets perfect performance.
The varAUC for this performance is "?". Can we make it zero?

**Comment by brandon-gallas** [comment]
Qi, You asked that I send you an input file that creates the problem. Here is one. Notice that when you click on the "AUC" button you will see the problem as well as in the output file.

 
[mcs.txt](https://github.com/DIDSR/iMRMC/files/715732/mcs.txt)

**Comment by qigongFDA** [comment]
This problem has been solved.

**Comment by brandon-gallas** [comment]
Great. I’m going to leave this open until I test it.
