### ISSUE TITLE
Add documentation for R scripts and create R package

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#117]
I have added a two R scripts in a new top-level directory "Rpackage"
simMRMC.R is essentially a simple version of iRoeMetz
iMRMC.R calls iMRMC.jar and collects the results from the "Analysis All Modalities" button

Please add a page in the iMRMC documentation about these scripts.
Please also create an R package to be uploaded to the CRAN repository.
The following will probably help, but there are likely many other resources to guide you:
ftp://cran.r-project.org/pub/R/doc/contrib/Leisch-CreatingPackages.pdf

**Comment by qigongFDA** [comment]
Beta version exists here: https://github.com/DIDSR/iMRMC/tree/master/Rpackage
Need some more documentation.
