### ISSUE TITLE
Access to iRoeMetz source and documentation

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#129]
I'm looking at the iMRMC front page and the releases page and I don't see any links to the iRoeMetz documentation. Is it ready to share? If so, please make it available like the iMRMC documentation (from the front page and the releases page).

**Comment by brandon-gallas** [comment]
Actually, I don't see the iRoeMetz source either.
The title of the release should identify all three programs and the release itself should include all three programs.

**Comment by qigongFDA** [comment]
I update the ghpage index.html and release page for iRoeMetz manuals.
