### ISSUE TITLE
Set the locale of iMRMC to be US

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#131]

**Comment by brandon-gallas** [comment]
https://stackoverflow.com/questions/4553633/java-float-formatting-depends-on-locale

http://www.avajava.com/tutorials/lessons/how-do-i-set-the-default-locale.html

**Comment by qigongFDA** [comment]
I set the locale to US. Version 4.0.0 includes this update. Could close this issue?

**Comment by brandon-gallas** [comment]
Perfect.
