### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by huangzp2016** [DIDSR/iMRMC#138]
When I run simulation using doIMRMCfast() function, some time there will be a dialog box: Error occurs, DF-Hill was calculated to be 1.9999999999...set to be 2. I need to click the "OK" button twice before the simulation can go on. It is OK if I run only one simulation; however, this is a problem if I run simulation replicates with for loop.

**Comment by brandon-gallas** [comment]
Thank you. We will fix.

**Comment by qigongFDA** [comment]
Thank you for your message. I sent you a new temp version of iMRMC. I think it can solve your please.

**Comment by huangzp2016** [comment]
The problem is solved, Thank you.
