### ISSUE TITLE
Update warning reporting

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#142]
When iMRMC is run as a GUI and it encounters a warning reading the input file, a window opens to alert the user.
When iMRMC is run within RStudio with output directed to the console, there is no report of the warning.

Please print warnings to standard output before opening the window with the warning. That way, the user can see the warning in Rstudio.

**Comment by qigongFDA** [comment]
This warning bug is fixed in version 4.0.1

**Comment by brandon-gallas** [comment]
In addition to the issues about the warning. Please update error reporting. For example, if I read in a file that has a missing truth statement, the GUI will open a window describing the error.
![image](https://user-images.githubusercontent.com/12649789/42525097-4f39e2e0-8440-11e8-9eae-804ba032f012.png)

This error does not get reported to the (output) console, and there is no window to dismiss. In Rstudio, the user does not know what happened. The program hangs. The error needs to be reported to the console, and the iMRMC program needs to be shut down.

**Comment by qigongFDA** [comment]
I think this has been solved. Please check it.

**Comment by brandon-gallas** [comment]
Please document how errors are handled before and after the changes and document if all errors and warnings are treated the same way or if there are different groups.

**Comment by brandon-gallas** [comment]
Please document how errors are handled before and after the changes and document if all errors and warnings are treated the same way or if there are different groups.

**Comment by qigongFDA** [comment]
Create two methods in commandStartFunction:  displayConsoleError, displayConsoleWarning.

For GUI mode, error and Warning will display in a window and print out in console (same as before).
For command line mode, the Error and Warning will only print out in console. If it is an error, software will quit.
