### ISSUE TITLE
2x2 contingency table

### ISSUE THREAD

**Issue by captcoma** [DIDSR/iMRMC#154]
Thank you very much for providing iMRMC. 

I very appreciate that iMRMC can be used to estimate sensitivity and specificity: https://github.com/DIDSR/iMRMC/wiki/Estimate-sensitivity-and-specificity

Is there also a possibility to get the 2x2 contingency tables (true positive, true negative, false positive, and false negative) of these estimations using the R package?

Thank you for your help.

**Comment by captcoma** [comment]
I calculated these values directly from the raw data using the `table` command in R. I think there is no need to implement this in the iMRMC package.

**Comment by brandon-gallas** [comment]
I thought about this and was reluctant to do it, thinking it should be in the skill set of most R users. Then I wanted to serve iMRMC users...

Thanks for posting your comment. I think it is the right call.

ATB,
Brandon
