### ISSUE TITLE
Size analysis for clustered data iMRMC

### ISSUE THREAD

**Issue by vijaypshah** [DIDSR/iMRMC#164]
Thank you for wonderful iMRMC for MRMC analysis.

I need to estimate a study design size.  However, there is  correlated/clustered data (on average may be 8 lesion per patient and range can vary from 0 to 50/100 or more). I am not sure how to handle clustered data in the iMRMC while performing size the trial. 

We would like to estimate how many readers and cases are required for the trial. 
The study design is fully crossed (the same readers and cases are used in both modalities and all readers read all cases).
The reference standard truth is established. 

Primary hypotheses:
null hypothesis (H0_1): there is no difference in area under curve (AUC) between modality A and B
alternate hypothesis (H1_1): there is a difference in AUC between modality A and B
null hypothesis (H0_2): there is no difference in volume between modality A and B
alternate hypothesis (H1_2): there is a difference volume between modality A and B

Best Regards,
Vijay

**Comment by brandon-gallas** [comment]
Hellow Vijay,

I'm sorry I didn't respond earlier and your email got buried. Too busy here.

Anyhow, I'll say that your study doesn't sound like an ROC study. I would not refer to the data as clustered data like published in Obuchowski1997_Biometrics_v53p567. Your study sounds like an FROC (Free response, location-specific, ROC) study as described in these papers: Chakraborty2006_Acad-Radiol_v13p1187, Bandos2009_Biometrics_v65p247, Wunderlich2013_Med-Phys_v40p111903.

I'm sorry that iMRMC cannot handle location FROC data. I hope the references direct you to a solution to your problem.

Brandon
