### ISSUE TITLE
Applying MRMC framework to study design with multiple sonographers

### ISSUE THREAD

**Issue by joshrapkin** [DIDSR/iMRMC#169]
I am helping to design a study in which there are multiple readers and multiple images (cases) to determine if an image is of good quality. To show generalizability, we also want to show that it works across multiple sonographers who will be helping the study subjects obtain the images. Is there a way to determine the appropriate sample size per sonographer using the MRMC software? I know that we could calculate the sample size assuming one sonographer and then simply multiple the sample size by the number of sonographers. This seems like overkill though.

**Comment by brandon-gallas** [comment]
I'm sorry. I don't immediately know how to include multiple sonographers in an MRMC analysis. Perhaps there is a way to treat each sonographer as a different modality and use the MRMC components of variance and covariance. If you do such an analysis, please let us know. We would be happy to promote your method.

Best of luck,
Brandon
