### ISSUE TITLE
can iMRMC r package analyze split-plot design?

### ISSUE THREAD

**Issue by GigiPAN** [DIDSR/iMRMC#183]
Dear authors,

Thank you so much for offering iMRMC, a great tool for MRMC analyze. 

My question is, if I can do the analyze for a split-plot design in iMRMC r package? As I haven`t find a function specially for this design.

And I`ve tried directly use function doIMRMC() for a split-plot design and seems it works. 

Best Regards,
Gigi

**Comment by brandon-gallas** [comment]
There is no special function for a split plot study design. It's all about the data. Each row corresponds to one reader x case x modality observation. A fully crossed study will have more rows that a split plot study, assuming the number of readers and cases are the same. I'm glad you were successful.

You are sort of anonymous to me, GigiPan. Please update your profile with your real name and affiliation, or add your real name and affiliation as a reply.

**Comment by GigiPAN** [comment]
Hi Prof. Gallas,

Thank you so much for so prompt reply. 

My name is Zhemin Pan a PhD student major in biostatistics in Tongji University, Shanghai, China.

And our team has supported the analysis for several MRMC designed CAD studies, and do face with challenges that DBM method can not solve, and that`s why we turn to U statistic approach.

Thank you so much for your time!
