### ISSUE TITLE
example file - iMRMC

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DIDSR/iMRMC#19]
```
Dear,

For the iMRMC java software, I tried it with the example file named test.imrmc

I modified it to make it more understandable and more consistent. By instance, 
there are 4 and not 5 readers. I removed all the unessecary spaces. All the 
observers have the prefix "reader" and the 2 modalities do have the prefix 
"modality".

Please find attached the version I made.

Cédric

```

Original issue reported on code.google.com by `cedric.m...@free.fr` on 21 Jan 2015 at 8:44

Attachments:
- [test_modified.imrmc](https://storage.googleapis.com/google-code-attachments/imrmc/issue-19/comment-0/test_modified.imrmc)

**Comment by qigongFDA** [comment]
We have several sample input files at: https://github.com/DIDSR/iMRMC/tree/gh-pages/000_iMRMC/inputFiles
