### ISSUE TITLE
Enhancement - workflow and plots to explore number of readers and cases while sizing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DIDSR/iMRMC#23]
```
Please describe the desired enhancement:

Dear 

1 - It would be nice to get the best estimate of number of cases and number of 
readers for reaching a certain given as input statistical power.

2 - generate the graph and/or output file: power = f ( number of readers) for 
fixed number of cases

3 - generate the graph and/or output file: power = f ( number of cases) for 
fixed number of readers

Best regards
Cédric

```

Original issue reported on code.google.com by `cedric.m...@free.fr` on 27 Jan 2015 at 3:15

**Comment by brandon-gallas** [comment]
@koyousun

Yousun,

Please fix this issue. I could imagine manual entry of numbers of readers and cases, or a button to read in an inputfile, or both. Recently, we have been adding buttons to save data at different places in iMRMC (commits coming soon). I think we definitely want to be able to write the output of the results of the sizing experiment to a file. Feel free to launch a new window or whatever to accomplish the main goal of this issue. I don't think you need to plot the results, but that would be fabulous.

Brandon

**Comment by qigongFDA** [comment]
We have added a new feature of the sizing module that investigates many experiments sizes at once, we hope this is helpful.
