### ISSUE TITLE
Negative variance estimation result.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DIDSR/iMRMC#26]
```
I get negative variance values for some files with the error message attached.
Even if I proceed with MLE estimates, I don't get variance results. What should 
I do?
```

Original issue reported on code.google.com by `silv...@gmail.com` on 4 Mar 2015 at 12:21

Attachments:
- [Screen Shot 2015-02-23 at 11.17.49 AM.png](https://storage.googleapis.com/google-code-attachments/imrmc/issue-26/comment-0/Screen Shot 2015-02-23 at 11.17.49 AM.png)

**Comment by qigongFDA** [comment]
Brandon says to close
