### ISSUE TITLE
Need true labels for "input statistics charts" and "show study design"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DIDSR/iMRMC#29]
```
The actual reader ID's and case ID's are not shown in the figures. This makes 
it hard to debug errors in the input file.


```

Original issue reported on code.google.com by `Brandon.Gallas` on 7 Mar 2015 at 4:43

**Comment by brandon-gallas** [comment]
I just added you to this. You are creating look up tables that the user can see or print out.

**Comment by qigongFDA** [comment]
In 846 version of qigong branch, I add a button to show and export the relationships between index and ID for reader and case

**Comment by brandon-gallas** [comment]
Perfect
