### ISSUE TITLE
New features for ROC curve

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DIDSR/iMRMC#34]
```
1. Please allow the points of the ROC curves to be output to a file.

2. Please allow overplot of two or more modalities.

3. Please add a subtitle that shows the name of the input file.

```

Original issue reported on code.google.com by `Brandon.Gallas` on 15 May 2015 at 6:32

**Comment by qigongFDA** [comment]
I finished the tasks 1,3. For task 2, I think plot multiple modalities ROC curves into one plot might make the plot unclear.  Now, for each modality plot, there are 9 curves and 11 check boxes. If we want to overplot  more modalities, we will double or even triple the number of curves and check boxes. That might make end user confused.

**Comment by brandon-gallas** [comment]
The functionality was requested by an end user. Give it a try. Only offer two modalities at a time. I don’t think you need to double the number of checkboxes; let each checkbox correspond to one reader (or reader average) and both modalities. Yes, there may be many curves in the figure, but that would be their choice. If they are smart, they will choose to show only one average in both modalities.

Thanks for completing the other task that outputs the x,y points of the ROC curves.
That is awesome!

Brandon

**Comment by brandon-gallas** [comment]
Add a second pull down menu. Users can choose modality A from pulldown 1 and proceed to the plot. Or they can choose modality B from pulldown 2 and proceed to the plot. Or they can choose modality A from pull down 1 and modality B from pull down 2 and the proceed to the overplot of the curves from the two modalities.

**Comment by brandon-gallas** [comment]
Please use GitHub for discussions whenever possible, not email and not text. I am adding your latest email below.

From: Qi Gong [mailto:qigong@gwmail.gwu.edu] 
Sent: Tuesday, September 22, 2015 3:17 PM
To: Gallas, Brandon D.; Gong, Qi *
Subject: ROC plot

Hello Brandon,

As first attachment, when we click "Show ROC Curve", the "Choose
Modality and Reader" window will display. Now, it has a pulldown menu
with 2 options "1" and "2". Choose 1 will process modality 1, choose 2
will process modality 2.

As my understanding, you want to creat another pulldown menu in
"Choose Modality and Reader" window. Use first one to choose modality
1 and use second only to choose modality 2, If we want to overplot,
choose "1" in first pulldown menu and  choose "2" in second pulldown
menu.

Why we don't keep one pulldown menu. And just add one more option "1
and 2", as second attachment. User choose this to overplot two
modalities. It think this could make our software more compact. Thank
you.

Sincerely,
Qi
![roc pulldown_new](https://cloud.githubusercontent.com/assets/12649789/10048633/e1a4cb74-61e1-11e5-9760-f9d90f32a756.png)
![roc pulldown_old](https://cloud.githubusercontent.com/assets/12649789/10048632/e1a3d9da-61e1-11e5-970a-18b7987cbe84.png)

**Comment by brandon-gallas** [comment]
The reason for my suggestion is that some MRMC input files have more than two modalities. Your suggestion doesn't work for these input files.

Thanks, Brandon

**Comment by qigongFDA** [comment]
Hello Brandon,

I am sorry for late reply. OK, now I understand it. In future, we might have 3, 4 or even more modalities. If we only show them in one pulldown menu, we need to list all the combination of modalities. That will make the pulldown menu very long and complex. I will try to do it follow your suggestion.

**Comment by qigongFDA** [comment]
I finished the task2.
Now the ROC curve could display multiple modalities. 
1.When choosing modality, I change 1 pulldown menu to several check boxes. The ROC plot will display the modality that user choose. If user don't choose anything, software will display a error message.
2.In the ROC plot there are check boxes for each reader and average. All the check boxes control all modalities that user choose. (i.e. if user choose to display 2 modalities, each check box will control 2 curves)
3. export button could export all modalities data in ROC plot.
4. The Show ROC Curve button now is designed for display more than 2 modalities. But as we don't have input file with more than 2 modalities, we can't try it.  

![task2-1](https://cloud.githubusercontent.com/assets/12702285/10087468/f7d29060-62e1-11e5-8059-8f1c5e5bebeb.png)
![task2-2](https://cloud.githubusercontent.com/assets/12702285/10087470/fb0ab12c-62e1-11e5-94c8-acc5083e55c4.png)

**Comment by qigongFDA** [comment]
I duplicate our 2 modalities data to 4. The ROC plot is working we can choose any combination of 4 modalities. 

As the data is built by duplication, The ROC plot are overlap. But we could figure out there are 4 curve, and the legend approves that.

The export button could output all the modalities we choose. 
![4m2](https://cloud.githubusercontent.com/assets/12702285/10104346/481e26ca-6377-11e5-8610-79d2087fe373.png)
![4m1](https://cloud.githubusercontent.com/assets/12702285/10104352/4bcfdf84-6377-11e5-8138-1b423cba39ae.png)

**Comment by brandon-gallas** [comment]
Sounds good.

Is that everything for this issue?
I’ll test and if all looks good, I’ll merge.

Brandon

**Comment by qigongFDA** [comment]
Hello Brandon,

Yes, they are everything: 1. export button; 2 ovelplot; 3. subtitle.  Please check them and let me know, if you are not satisfied with them. Then I could update them. 

Have you approved my last pull request "copy the latest version from FDA svn trunk ". Do I need to submit a new pull request for these updates? Thank you.

Sincerely,
Qi

**Comment by brandon-gallas** [comment]
I hope to check and merge all your changes in the coming week.

**Comment by brandon-gallas** [comment]
Well done
