### ISSUE TITLE
Let Show ROC Curve button works for not fully crossed data

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/iMRMC#41]
If the the input file is not fully crossed. (i.e. Some modalities not read by all readers), the ROC button produce error. Solve this problem to let the software more robust.

**Comment by qigongFDA** [comment]
In 846 version of qigong branch, ROC curve could plot for not fully crossed input data.

**Comment by qigongFDA** [comment]
After add code for issue 42, ROC curve has a little problem. The input file has same data for modality 1,3 and 2,4. But now ROC curve is not exactly overlap for this two groups.

**Comment by qigongFDA** [comment]
In generateROCpoints function, I find the keyedData is loaded correctly. 

And I find out the reason for this problem might be the variable max and min ( about 320 lines in InputFile.java). Our code generate ROC data modality by modality. For each modality, we calculate minimum and maximum score for whole modality data, and set 100 threshold steps in side them. As the maximum and minimum is for whole modality, but not each reader, the ROC curve might not overlap exactly. 

For example, we have 3 readers and 1 modality A. Reader 2 give highest and lowest score. We duplicate the data and named it as modality B, and delete all the data about reader 2 in modality B. When we processing modality A, the maximum and minimum for ROC is reader 2's score. But when we processing modality B, the maximum and minimum are the highest and lowest score from reader 1 and 3. Now even two modalities have same data for reader 1 and 3, the threshold check points for ROC cruve are different. Then the curves for reader 1,3 in two modalities can't overlap exactly. @brandon-gallas

**Comment by brandon-gallas** [comment]
Perfect
