### ISSUE TITLE
Problem about 1 distribution ROC curve

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/iMRMC#42]
Hello Brandon,

When I do the not fully crossed ROC curve task, I find a problem. I build an input file. A reader only reads one case for one modality, and reads all other modalities cases. The java gives me error. I think the error is coming from that reader and modality, there is only one PDF (because the case that reader reads should either normal or disease.). Then we can't get one of TPF and FPF, and can't get ROC. 

I ask Frank and Weijie about this. They answer is, we can't get ROC curve if truth of cases are all positive or negative.

I could add one check function in imrmc to detele all the data for that reader & modality.  Or do you have any idea to make the ROC curve. Thank you

**Comment by brandon-gallas** [comment]
Hi Q,

You have generally identified the problem and the fix. When describing the fix, please identify where in the code you expect to make changes. I think changes should happen in InputFile.verifySizesAndGetIDs. If a reader does not read at least 2 normal cases and 2 disease cases for a modality, delete the scores for that reader and modality. Also alert the software user to the fact that iMRMC is “ignoring” those scores. This requires an input file to test. I have (re)created a folder that held input files for debugging. You can find it at https://github.com/DIDSR/iMRMC/tree/gh-pages/000_iMRMC/inputFiles/forDebugging Please put useful input files in this directory. Try and name the file to describe its purpose, and then add more details in the free-text portion of the input file.

Thanks for creating this issue and finding a solution!

Brandon

**Comment by qigongFDA** [comment]
Hello Brandon,

OK. I just added a new input file to that folder.

When I asked Frank, he said you once mentioned some method. It could help us calculate AUC even all the data have same truth. I thought you might also have method to plot ROC curve under that situation. Thus, I just mentioned another alternative method briefly, and hadn't looked the code and found a proper place to put the function. I will try to describe them more detail in future. Thank you.

Sincerely,
Qi

**Comment by brandon-gallas** [comment]
I don’t understand most of your comment. Let’s talk about this during our 1on1, Tuesday.

**Comment by brandon-gallas** [comment]
Got it. Thanks. Done.
