### ISSUE TITLE
MLE check box problem

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/iMRMC#45]
When we check the MLE check box, the software displays correct total var. But in Eclipse, total var is incorrect. @brandon-gallas

**Comment by brandon-gallas** [comment]
Just clarifying:
There are three locations where the variance analysis are shown. Above the table of variance components, to the right of the table of variance components, and in the eclipse console. It appears that the total variance to the right of the table of variance components is different from what is used above the table of variance components and what appears in the console.

Thanks for creating this issue.

Brandon

**Comment by brandon-gallas** [comment]
Good one.
