### ISSUE TITLE
Allow user to input analysis summary

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/iMRMC#48]
We should add a new feature to allow user input the analysis summary for prediction analysis. The summary is the exported by “Save to File” Button. @brandon-gallas 
We could follow this procedure to do it.
1.	Reorganize exported summary
We don’t have to load everything from summary. What we need are AUC values, BDG Results and sample sized. 
We should put these data together and use “BEGIN SUMMARY” and “END SUMMARY” to include them
2.	Update load input feature.
Both raw input file and summary should be in .imrmc format. Their difference is the raw input data uses “BEGIN DATA”, but the summary data uses “BEGIN SUMMARY”. Users should choose what they want to do from a pull down menu before they input file.
3.	Calculate all others useful data
We should calculate other parameters like BCK and OR by the 3 groups data we loaded. 
4.	Prediction analysis
We should let prediction function could use summary file data to do the analysis.

**Comment by qigongFDA** [comment]
This is a test message for Git Hub"at" feature.

**Comment by brandon-gallas** [comment]
Not sure if I said so, but this is the highest priority in the MRMC project. You did a great job creating the issue. I'm assigning it to you. Please do it when you finish your current eeDAP tasks.

**Comment by qigongFDA** [comment]
1. Reorganize exported summary. Now Useful data is included by  “BEGIN SUMMARY” and “END SUMMARY” .
2. Load all useful data to DBrecord
3. Add input summary option in the pull down menu.
Problem,
1. Only load one row BDGcoeff. I set the first 3 row to same number and 4th row to "1"
2. Summary doesn't have BDGbias
3. Can't input to StatTest (DBRecod.java line 590)

**Comment by qigongFDA** [comment]
1. Reorganize exported summary. Now Useful data is included by “BEGIN SUMMARY” and “END SUMMARY” .
2. Load all useful data to DBrecord
3. Add input summary option in the pull down menu.

Problems:
1. Summary only has one row BDGcoeff. I set the first 3 row to same number and 4th row to "1"
2. Summary doesn't have BDGbias
3. I could load summary data to DBRecord function. But I can't update DBRecordStat and input it to StatTest (DBRecod.java line 590)

**Comment by brandon-gallas** [comment]
We should sit down together to iron out the problems you identify.

Brandon

**Comment by brandon-gallas** [comment]
Here is the matrix that maps unbiased BDG to biased BDG
![unbias2bias](https://cloud.githubusercontent.com/assets/12649789/11158974/e371cae0-8a29-11e5-9d6d-23291e216966.png)

Here is the matrix that maps biased BDG to unbiased BDG
![bias2unbias](https://cloud.githubusercontent.com/assets/12649789/11158980/f1e2f95a-8a29-11e5-8764-6ade8f583248.png)

**Comment by brandon-gallas** [comment]
The matrices in my last comment only work when a study is fully crossed. Please validate the input of summary data with analysis data.

**Comment by qigongFDA** [comment]
1. Reorganize summary file.
2. Create 2 new cards, InputSummaryCard and InputStartCard.
3. Add summary load functions in InputFile.java (line 628)
4. Add DBRecordStatFillSummary function in DBRecord.java to process summary data (i.e. unbias to bias, coeff, var)
5. Software could remember last input file and export file directories. Use 2 variables in GUInterface (line 96) to save the directory.

**Comment by brandon-gallas** [comment]
Nice job. I think this is done. Correct me if I am wrong.
