### ISSUE TITLE
Instructions for non-statistician

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#49]
Suggestion from software user:
Please add instructions and guides for non-statisticians: "non-statistician users can don't have to read this section and jump to XXX" in the manual."

**Comment by brandon-gallas** [comment]
@aanam 

Amrita,

The case study on sizing a study with Silvina is intended to address this issue. Please use this issue to document progress and communicate.

Brandon

**Comment by aanam** [comment]
Hi,
I am hoping the document Jessica is developing will address this issue - "how to size a study". We can take help from Silvina on different steps.

**Comment by qigongFDA** [comment]
The documentation has been updated.
