### ISSUE TITLE
Add glossary of terms to the documentation

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#51]
@aanam @qigongFDA 

Amrita and Qi,

This might be an easy start for Jessica, to make a list of all the terms that she does not know in the MRMC documentation and to create the glossary in DrExplain. This list might be very long, no problem. For very standard terms, we can include links to wikipedia. For other terms, you can try and describe them. Then I can play clean up: review and update your contributions or add descriptions myself.

This issue was suggested by a user who also said:
Radiologist investigators and journal readers already have so many jargons to learn, other than "covariate" and "figure of merit".

Brandon

**Comment by qigongFDA** [comment]
Brandon says close it for now.
