### ISSUE TITLE
Input data interface needs to be more user-friendly

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#52]
@koyousun

Yousun, Kyoung made this suggestion in Feb (2/9/15). Since then we added several error checking and warnings to inform the user. I'm not sure if he has experienced this error checking and warnings. Maybe they are adequate. Regardless, please confer with Kyoung and find out what he thinks might make the process more user-friendly. 

Brandon

**Comment by qigongFDA** [comment]
Brandon says close it
