### ISSUE TITLE
Update documentation header and footer

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#54]
Brandon,

Do something like you did for the eeDAP documentation.
Header should have "Github website: https://github.com/DIDSR/iMRMC"
Footer should have "Size and Analyze Multi-reader Multi-case Reader Studies"

Thanks,
Brandon

**Comment by qigongFDA** [comment]
I add Header and Footer for PDF and HTML version manuals. We need some discuss about whether we want to add comments and sharing to the manual (i.e. Facebook Like, Google Plus)

**Comment by brandon-gallas** [comment]
Please implement this header and footer for eedAP.
Also implement the management of the draft and published versions of the documentation.

Also,
Please show Amrita what you did in the header and footer.
Please show Amrita how you are organizing the draft and published versions.
Then message me and I will close this issue.

@aanam 

Amrita, Please update the mcs package as Qi will show you.

**Comment by aanam** [comment]
Ok. I will work with Qi on this.

On Tue, Nov 10, 2015 at 1:54 PM, Brandon Gallas <notifications@github.com>
wrote:

> Please implement this header and footer for eedAP.
> Also implement the management of the draft and published versions of the
> documentation.
>
> Also,
> Please show Amrita what you did in the header and footer.
> Please show Amrita how you are organizing the draft and published versions.
> Then message me and I will close this issue.
>
> @aanam <https://github.com/aanam>
>
> Amrita, Please update the mcs package as Qi will show you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DIDSR/iMRMC/issues/54#issuecomment-155530065>.
>



-- 
=================================
Amrita Anam,
Teaching Assistant
Department of Information Systems, UMBC
1000 Hilltop Circle, Baltimore, MD 21250
=================================

**Comment by qigongFDA** [comment]
Hello Brandon,

OK. I will do it. Thank you.

Qi

**Comment by qigongFDA** [comment]
I add the footer and header to eeDAP manual. And build the draft and published versions of it. I also show Amrita how to do it. Please have a check and close this ticket. Thank you.

**Comment by brandon-gallas** [comment]
Agreed. GIT does not allow copy or rename files or folders. So do not use "SVN-copy". To accomplish copy or rename, use regular copy-paste, SVN-add the copy, SVN-delete the original.

Thanks for doing these updates to documentation. I am changing the assignee from Qi to Amrita.

Amrita, let me know when you update the header and footer and create draft versions of the mitotic count simulation documentation. Then I can close this ticket.

**Comment by aanam** [comment]
Added header and footer to the documentation of mitotcCountSimulation with link to release page
http://didsr.github.io/mitoticCountSimulation/userManualHTML/index.htm

**Comment by qigongFDA** [comment]
Hello Amrita, 

I read the HTML manual. The footer and header are great. I think if we want to follow the imrmc and eedap manual format, we might need the footer and header for pdf version too. 

Qi

**Comment by qigongFDA** [comment]
I update the header of iMRMC and EEdap publishing and draft manuals to link to release page.

**Comment by brandon-gallas** [comment]
Yep. Please add header and footer information to mitotic count simulation *PDF* documentation.

**Comment by aanam** [comment]
updated the pdf document http://didsr.github.io/mitoticCountSimulation/userManualPDF/mcsUserManual.pdf

**Comment by brandon-gallas** [comment]
Thanks! Closing this issue.

**Comment by brandon-gallas** [comment]
Sorry, I didn't read the footnote closely. I would like to change the focus to the agreement analysis instead of the simulation.
Change, "Simulates survival times and mitotic counts to validate reader variability "
to
"MRMC agreement analysis with simulation for validation"

**Comment by aanam** [comment]
Updated the footer to keep focus on agreement
http://didsr.github.io/mitoticCountSimulation/userManualHTML/index.htm
http://didsr.github.io/mitoticCountSimulation/userManualPDF/mcsUserManual.pdf
