### ISSUE TITLE
New workflows for sizing a reader study

### ISSUE THREAD

**Issue by SilvinaZabalaTravers** [DIDSR/iMRMC#55]
It would be very useful if the sizing section of the software could work 'on the opposite direction', I mean to estimate the number of readers and cases necessary to achieve a preselected value of power, effect size and significance level. Maybe it is not possible to estimate both readers and cases at the same time but one of them could be used as input. 

I.e For 10 readers and (all the other inputs) how many cases in total do we need?

**Comment by brandon-gallas** [comment]
In addition to the workflow you describe, we will also allow the user to explore multiple # of readers and # of cases at one time instead of one combination at a time.

**Comment by qigongFDA** [comment]
1. Create exploreExpSize.java file in mrmc.chart to export multiple number of readers and cases results
![ees](https://cloud.githubusercontent.com/assets/12702285/11753647/48d0e0a6-a014-11e5-88df-30ba80b43984.png)
We preset #reader pool= [5, 10 , 15, 20] 
#normal/disease pool = [32, 64, 128, 256, 512, 1024, 2048, 4096, 8192]
Software could display result for any pair.
There are 3 pull down menu and one button in the window.
1.1 First menu: User could use it to switch display pairs (reader vs normal, reader vs disease, normal vs disease)
1.2 Second menu :  User could use it to choose a value for the third variable
1.3 Third menu: Switch between S.E. and BDG power.
1.4 Export button: export current displayed table to csv file.  

2. Add a button "Expore Experment Size" in size panel to enable exporeExpSize

3. Create an error message to alert users, if they click "Expore Experment Size" before doing analysis.

**Comment by qigongFDA** [comment]
Add doFullSize variable in exploreExpSize.java to avoid display Hillis error window.

**Comment by qigongFDA** [comment]
Debug power part problem. 

I think we could close the issue

**Comment by brandon-gallas** [comment]
Done. Nice Job.
