### ISSUE TITLE
Should allow .csv files along with .imrmc files as inputs to the software

### ISSUE THREAD

**Issue by aanam** [DIDSR/iMRMC#63]
Check the errors- .csv file saves "," s where the columns are not same size id saved from excel.

**Comment by qigongFDA** [comment]
Now the software could input both .imrmc and .csv raw format data and summary file

I solved the problem in InputFile.java about 580th line. For csv file, the software will delete all pending ","s, when it saves input file data into fileContent. 

I think all other input file process functions are based on fileContent. Thus, if we made fileContent has original format, we don't have to change any other code to load raw and summary file. And it is convenient if we have the third or even more kinds of input file in future.

**Comment by brandon-gallas** [comment]
Update documentation and show me during our one-on-one. I'd like to pull this into the master when ready.
