### ISSUE TITLE
 Need output reports from iRoeMetz

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#64]
This is very similar to issue #30,  "Need output reports from iMRMC".
iRoeMetz has two basic functions: ![temp](https://cloud.githubusercontent.com/assets/12649789/11131730/1c5b3434-895a-11e5-8d7d-a8b735d9bd37.PNG)
1. Simlate MRMC studies -> analyze
2. Derive and calculate analysis results

Item 2 is how we validate item 1.
Both items produce analysis results similar to what is produced in iMRMC.
![capture](https://cloud.githubusercontent.com/assets/12649789/11131844/a0d7c5a6-895a-11e5-9531-765f94c37f3a.PNG)

I would like you to add a button to both analysis results windows that prints the summary output to a file.

See me if you have questions.

**Comment by qigongFDA** [comment]
Almost all the update is in RMGInterface.java file
1. Add a button at the bottom of the windows to export.
2. Two button share same Listener
3. Create genReport method in RMGInterface.java to write statpanel and table information to export file. 
4. Create genMCresults method to write MC result to export file.

**Comment by qigongFDA** [comment]
There are 2 more things need to do 
1. Let "Save Components to File" button export "study Design" line's information.
2. Compare simulation average summary result with individual simulation result by iMRMC. The power part might have some problems.

**Comment by qigongFDA** [comment]
"Save Components to File", " Populate Components from File" and export button are working well.

**Comment by brandon-gallas** [comment]
I am logging your email to me here. This may not be the best place for this, but it belongs somewhere.


Hello Brandon,

I got reply from GITHUB yesterday. It also creates a new branch from a previous version like your method. The difference is  his method does it in GITHUB web page.

What I will do is following
1.	Make these changes in “qigongBeforeValidation” 
a.	Debug power part in “explore experiment size”.
b.	Reorganize Size output and delete summary from it
c.	In iRometz change simulation window title
d.	In statpanel output, delete study size information and two “*****” lines
e.	I will NOT do what we discussed yesterday in this branch and hold them with validation.
2.	Create a pull request from ““qigongBeforeValidation” to “Master” and wait you check it out
3.	Create a pull request from ““qigongBeforeValidation” to “qigong” and check it out by myself, then continue work on validation

I will start these works this afternoon or next Monday. Please correct me if anything is wrong. Thank you very much.

Best Regards,
Qi

From: Francis Batac (GitHub Staff) [mailto:support@github.com] 
Sent: Thursday, February 25, 2016 6:09 PM
To: Gong, Qi *
Subject: Re: merge from previous version

Hi Qi,
Thanks for writing back. My apologies for writing an incomplete reply earlier -- I failed to mention two more steps:
•	Create a branch from 7bf42b0 
•	Create a pull request comparing qigongMid (base) to 7bf42b0 
Create a branch from 7bf42b0 
First, navigate to the commit:
https://github.com/DIDSR/iMRMC/commit/7bf42b0dbef60ec510901783ccc2f01373de8a45
Next, click "Browse Files" at the top right corner of the commit message You should be led to the tree for 7bf42b0:
https://github.com/DIDSR/iMRMC/tree/7bf42b0dbef60ec510901783ccc2f01373de8a45
Where it says "Tree: 7bf42b...", click that and create a new branch from the tree. You can name it anything you'd like -- I just named it 7bf42b0 for clarity.

![fig](https://cloud.githubusercontent.com/assets/12649789/13359550/e06f0ad2-dc82-11e5-8580-b3e1f223bbdd.png)
 
Create a pull request comparing qigongMid (base) to 7bf42b0 
Now that you've created a branch from 7bf42b0, you can now create a pull request with qigongMid as the base branch.
First, navigate to the repo's pull request page:
https://github.com/DIDSR/iMRMC/pulls
Next, click the green button that says New Pull Request.
For the base branch, use qigongMid. For the compare branch, use the branch created from 7bf42b0.
Now you can create a pull request and go on to merge the changes like you originally asked for. 
Please let me know if you have any questions about this!
All the best,
Francis
@francisfuzz
GitHub Support

**Comment by brandon-gallas** [comment]
Done. Excellent work.
