### ISSUE TITLE
Comments on Documentation

### ISSUE THREAD

**Issue by SilvinaZabalaTravers** [DIDSR/iMRMC#66]
Page 5 & 11.  I see you have a <TODO> comment which looks like internal between-developers comment. You might want to write something like section under construction or similar.

Page 6.  The software can analyze data from a reader-study of two modalities that is fully crossed with readers and cases paired across modalities (every reader reads every case in two modalities). 
It also analyzes not-fully crossed studies, right? You might want to clarify this to encourage more users to try it. This comment in page 17 might be appropriate as an alternative: iMRMC can handle data that is not fully-crossed for any number of modalities, though only two of those modalities may be used at a time for variance analysis.

Page 9. In particular, the user specifies the new study design with number of split-plot groups, pairing of readers, pairing of cases... 
As far as I know the split-split version of the iMRMC is the beta I have in my laptop. Maybe you missed describing it as a future addition?

**Comment by brandon-gallas** [comment]
Thanks for the comments. The split-plot study design will be available soon. We need to run some validation simulation studies.

Amrita, please address these comments and visit Silvina some time to see if she has some more comments, especially regarding data formatting (Sect. 4.4.2).

**Comment by brandon-gallas** [comment]
Consolidating issue #68 with this issue.

Create a discussion on how to check for data errors with “Input Statistics Charts”, “Show Study Design”, “Show ROC curve”. Put this documentation in the same section where we talk about the data format.



Additional updates to documentation:
1. Section 4.4 Data Format for ROC Ratings should include screenshots of a sample data with detailed description of each section and limitations with extra commas or blank spaces

    Add error messages with the input data file as many as possible so the reader knows where and what the mistake is in the file

    Mention in the documentation that the software can handle score from 0-100

    If possible the software could read data from each reader and put it all together in the .imrmc format

**Comment by aanam** [comment]
@ajhandoko will be also working on improving the documentation.

**Comment by qigongFDA** [comment]
This is done.
