### ISSUE TITLE
Checking the changes in the gui 

### ISSUE THREAD

**Issue by aanam** [DIDSR/iMRMC#67]
Hi Qi,
Could you please check the changes i made in the files SizePanel.java(issue #58, #59) and StatPanel.java(issue #60 , #61 ). They are in my iMRMC fork.

**Comment by aanam** [comment]
I have made the changes we talked about.
1. removed the infinity sign 
2. changed values of reject null to fit in the screen

**Comment by qigongFDA** [comment]
I checked the updates. Your updates are working. Good job.

There are some things could be improved. 
1. I find the updates you made are not under your fork. You directly made changes to DIDSR/iMRMC/master. Please double check your working directory.
2. For issue #58, please also change sqrt(total var) in StatPanel.
3. For issue #59, please also delete T Statistic in StatPanel. And in SizePanel, when I click "Szie a Trial" button, "Stat" appears again. 

 If you face problems about them, free feel to ask me. Thank you.

Qi

**Comment by aanam** [comment]
Ok. I will check and get back to you


On Thu, Nov 19, 2015 at 3:21 PM, Qi Gong <notifications@github.com> wrote:

> I checked the updates. Your updates are working. Good job.
>
> There are some things could be improved.
> 1. I find the updates you made are not under your fork. You directly made
> changes to DIDSR/iMRMC/master. Please double check your working directory.
> 2. For issue #58 <https://github.com/DIDSR/iMRMC/issues/58>, please also
> change sqrt(total var) in StatPanel.
> 3. For issue #59 <https://github.com/DIDSR/iMRMC/issues/59>, please also
> delete T Statistic in StatPanel. And in SizePanel, when I click "Szie a
> Trial" button, "Stat" appears again.
>
> If you face problems about them, free feel to ask me. Thank you.
>
> Qi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DIDSR/iMRMC/issues/67#issuecomment-158186192>.
>



-- 
=================================
Amrita Anam,
Teaching Assistant
Department of Information Systems, UMBC
1000 Hilltop Circle, Baltimore, MD 21250
=================================

**Comment by aanam** [comment]
Hi I have made the changes you suggested.

**Comment by qigongFDA** [comment]
I checked them. They are working correctly. Great job. But the change is still under DIDSR/master. When you free, you could come to my office or lab. We could try to fix it together.

**Comment by aanam** [comment]
Hi,
I have added the hillis approx button issue #62. Please check it and let me know if it is fine.
