### ISSUE TITLE
Document Data Checks

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#68]
Create a discussion on how to check for data errors with “Input Statistics Charts”, “Show Study Design”, “Show ROC curve”. Put this documentation in the same section where we talk about the data format.

**Comment by brandon-gallas** [comment]
Additional updates to documentation:
1. Section 4.4 Data Format for ROC Ratings should include screenshots of a sample data with detailed description of each section and limitations with extra commas or blank spaces 

2. Add error messages with the input data file as many as possible so the reader knows where and what the mistake is in the file

3. Mention in the documentation that the software can handle score from 0-100 

4. If possible the software could read data from each reader and put it all together in the .imrmc format

**Comment by aanam** [comment]
Shall I work on this?

**Comment by brandon-gallas** [comment]
Consolidated this issue into #68
