### ISSUE TITLE
Summarize updates

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#74]
Qi please review all the commits since version 2p7 and summarize them. We want to highlight new features and bugs fixed. We will post this summary on the release page.

**Comment by qigongFDA** [comment]
I create the first draft of the summary. Please have a look. Thank you.
[iMRMC2p8_updates.txt](https://github.com/DIDSR/iMRMC/files/52252/iMRMC2p8_updates.txt)

**Comment by brandon-gallas** [comment]
I have edited and saved the document you sent in the root of the master branch. I renamed it to UPDATES.md (https://github.com/DIDSR/iMRMC/blob/master/UPDATES_iMRMC.md)
Please update this file to include previous updates given at the google code site (https://code.google.com/p/imrmc/wiki/iMRMCVersionHistory)
Also, create an analogous file for iRoeMetz based on the history at the goolge code site https://code.google.com/p/imrmc/wiki/iRoeMetzVersionHistory.

**Comment by qigongFDA** [comment]
I edit UPDATE_iMRMC.md.file and create UPDATE_iRoeMetz.md file following google code site. 

There are 3 problems for iMRMC updates
1. For iMRMC, I only move software updates summary to GITHUB. And didn't move manual updates information (like iMRMC User Manual Version 2p2)

2. For iMRMC, I can't find iMRMC Application version 2p2 in google code site

3. For iRoeMetz, there is no content in Version 1p0 update summary. Do we still need to mention this version in  UPDATE_iRoeMetz.md?

**Comment by brandon-gallas** [comment]
Looks good to me.
