### ISSUE TITLE
Export Sizing Result Button

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/iMRMC#76]
Add a button to export sizing result separately. And change current export button to only export summary data and statpanel output.

**Comment by qigongFDA** [comment]
We might need to create an independent class to build export file.

**Comment by qigongFDA** [comment]
1. Add new button for export size result. The original button only exports statpanel and summary.
2. As discussed with Brandon, I build a new class exportToFile in chart package for export analysis results. It includes 4 methods,
 * 1. exportStatPanel: export statpanel and table
 * 2. exportSizePanel: export sizepanel in imrmc gui 
 * 3. exportMCvariance: export MC variance result in iRoeMetz simulation. 
 * 4. exportSummary: export analysis summary.
"Save to file", "Save size" in iMRMC and two export buttons in iRoeMetz are using this class. ( I haven't deleted original genReport function)

**Comment by qigongFDA** [comment]
Add doFullSize variable in exploreExpSize.java to avoid display Hillis error window.

**Comment by qigongFDA** [comment]
I think we could close this issue

**Comment by qigongFDA** [comment]
1. "Save Size" button doesn't export summary.
2. In exportToFile class, add exoprtiRoeMetzSet method to export IRoeMetz setting. Separate original 4 methods to 6 for different export requests. 

 I think we could close this issue

**Comment by brandon-gallas** [comment]
Done. Nice Job.
