### ISSUE TITLE
Link to Silvina's talk

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#78]
@ajhandoko @aanam 

Hello Ladies, I have uploaded Silvina's RSNA talk to the gh-pages branch (000_resources). Please include this as a reference and link to it. Also do the same for the other resources.

Thanks,
Brandon

**Comment by aanam** [comment]
Oh great! Can wait to check it out.

**Comment by aanam** [comment]
I posted the link on both the documentation (size a future study, additional notes and reference ) and the index page on the draft.
http://didsr.github.io/iMRMC/000_resources/Zabala2015_RSNA_talk.pdf

**Comment by qigongFDA** [comment]
Brandon says close it
