### ISSUE TITLE
Update the updates files

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/iMRMC#92]
Please update the following based on the recent commits to the master.
https://github.com/DIDSR/iMRMC/blob/master/UPDATES_iMRMC.md
https://github.com/DIDSR/iMRMC/blob/master/UPDATES_iRoeMetz.md

**Comment by qigongFDA** [comment]
There are the updates for iMRMC and iRoeMetz. After final check, we could release new version.
[iRoeMetzUpdates.txt](https://github.com/DIDSR/iMRMC/files/342345/iRoeMetzUpdates.txt)
[imrmcUpdates.txt](https://github.com/DIDSR/iMRMC/files/342344/imrmcUpdates.txt)

**Comment by qigongFDA** [comment]
Could we close this issue?

**Comment by qigongFDA** [comment]
Brandon acknowledges the issue is fixed
