### ISSUE TITLE
Large number of trails validation problem

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/iMRMC#94]
When the number of trails equals to 100,000, iRoeMetz might fail sometimes. The error happens in 1250 line of RMGUInterface (results[taskNum] = allTasks[taskNum].get();)

**Comment by qigongFDA** [comment]
At first, I thought the error is due to the seed of RNA is corresponding small with number of trails. But after following test. I find my assumption might be wrong
![image](https://cloud.githubusercontent.com/assets/12702285/13795439/1c888fea-ead7-11e5-8666-18e74ddcc4d5.png)

**Comment by qigongFDA** [comment]
When the seed = 123456, we have problem on trail #68447. 
in SimRoeMEtz.java RandomVariateGen gaussRV generates an "Infinity", That makes RCB[0][14]=infinity, and (reader000 normal000014) reading result to infinity. I think this is the reason.

**Comment by qigongFDA** [comment]
I add 2 if statements in RimRoeMetz.java. They will check if number generated gaussRV is "Infinity". If it is "Infinity", software will generate a new number. I also test the speed of it. Result show the if statement doesn't affect time a lot.

![image](https://cloud.githubusercontent.com/assets/12702285/13892371/5bfb63f2-ed2d-11e5-8858-e630456c1ee2.png)

**Comment by qigongFDA** [comment]
I think we can close this issue

**Comment by brandon-gallas** [comment]
Well done.
