### ISSUE TITLE
New button to export statistical analysis result for computer reading

### ISSUE THREAD

**Issue by qigongFDA** [DIDSR/iMRMC#95]
We need to new button to export statistical analysis result for computer reading. 
1. The output file should in .csv format
2. All the analysis result should be in one line.
   2.1 There are 2 lines in the output file first line is head, and the second line is result
   2.2  title order: 
  input file, date, iMRMC Version, NR, N0, N1, ModalityA, Modality2, AUCA, VarAUCA, AUCB, VarAUCB, AUCA-AUCB, totalVar, Normal p-value,Noraml botCI,Normal TOPCI,dfBDG,BDG p-value,BDGbotCI,BDGpotCI,dfHills,Hills p-value,Hills botCI,Hills potCI
   3.2 For the item we didn't analysis, use N/A (For example, for not fully crossed study, 4 Hills items are N/A)

**Comment by qigongFDA** [comment]
I add the new button, and create a new method exportStat is exportToFile.java to achieve it.

**Comment by qigongFDA** [comment]
I think we can close this issue

**Comment by brandon-gallas** [comment]
Fix spelling errors, eliminate spaces, and other edits for column labels.
input file -> inputFile
iMRMC Version -> iMRMCversion
ModalityA -> modalityA
Modality2 -> modalityB
VarAUCA -> varAUCA
VarAUCB -> varAUCB
AUCA-AUCB -> AUCAminusAUCB
totalVar -> varAUCAminusAUCB
Normal p-value -> pValueNormal
Normal botCI -> botCInormal
Normal TOPCI -> topCInormal
BDG p-value -> pValueBDG
BDGbotCI -> botCIBDG
BDGpotCI -> topCIBDG
Hillis p-value -> pValueHillis
Hillis botCI -> botCIHillis
Hillis potCI -> topCIHillis

**Comment by brandon-gallas** [comment]
Have you fixed the spelling errors? If so let's merge into the master.

Also, I realize that you are missing outputs that I was just looking for. The p-values and confidence interval information for the individual modalities. Please add these.

**Comment by qigongFDA** [comment]
Hello Brandon,

Yes, I fixed the spelling errors. But I didn't know we should output those information for individual moralities. Do you want me add them first or merge first? Thank you

**Comment by brandon-gallas** [comment]
Thanks for your discussion today. I forgot that I can do a single modality analysis from the gui and save the single modality results that way. That will work for me.

**Comment by qigongFDA** [comment]
I think we could close this issue

**Comment by brandon-gallas** [comment]
Good work. This issue is closed.
