### ISSUE TITLE
Suggestion: Export to .pdf file

### ISSUE THREAD

**Issue by SilvinaZabalaTravers** [DIDSR/iMRMC#97]
Avoids the need for matlab to read exported file. Makes it easier to share results. Thanks!

**Comment by brandon-gallas** [comment]
@qigongFDA 

Good idea, but I should make sure I know what you want to be a pdf. Are you referring to the statistical analysis?

Right now we output the study results in a bit of a messy format: not very good for humans to use and not very good for computer programs. We are rethinking this and I think we will output at least two files. One that is pdf (good for humans) and one that is csv (good for computers).

Let me know if I am on the right track.

**Comment by SilvinaZabalaTravers** [comment]
I am referring to the MRMC summary that we export with the 'Save to file' button.  
Two files pdf and cvs will be great.

**Comment by qigongFDA** [comment]
Merge and release a new version. It can export pdf statistical analysis result. Close
